project_id = "eydjvxowjmlpzpdrlabe"

[functions.fetch-zora-nfts]
verify_jwt = false

[functions.fetch-twitter-feed]
verify_jwt = false

[functions.fetch-opensea-nfts]
verify_jwt = false

[functions.manifest]
verify_jwt = false